### ISSUE TITLE
Create a workflow that checks for aztec-packages releases

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/aztec-starter#102]
Create a workflow that runs nightly that checks for the latest release from aztec-packages, and updates the version if possible.

Requirements: 
- It should run every night
- It should get the latest non-nighlty version release from [aztec-packages ](https://github.com/AztecProtocol/aztec-packages)
- It should update the starter to use that version
- It should create an issue on this repo and tag @AztecProtocol/devrel if the job fails

Steps to update:

Once the latest version is fetched, this repo can be updated to the latest by running:
- `yarn update`
- Open a PR with the changes

Recommendation from Claude.ai

```yaml
name: Create PR with Changes
on: [push]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create new branch
        run: |
          git checkout -b auto-update-$(date +%s)
      
      - name: Make your changes
        run: |
          # Your workflow logic here
          echo "Updated at $(date)" > updated.txt
          npm run build  # or whatever your process is
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-update from workflow" || exit 0
      
      - name: Push branch and create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD
          gh pr create \
            --title "Automated updates from workflow" \
            --body "This PR contains automated updates generated by the GitHub Actions workflow." \
            --head $(git branch --show-current) \
            --base main
```
